### PR TITLE
Allow queries to be deleted

### PR DESCRIPTION
**Pull request by christophervalles**
Well is not actually deleted they go archived ala dashboards. This allows you to delete your own queries and if your group has the permission "delete_queries" people from that group can delete other's queries

### CODE REVIEW

**Comment by jcbozonier** [comment]
Hey when is this getting merged in?

**Comment by arikfr** [comment]
@jcbozonier this branch needs to be rebased and updated. I started doing this on this (see [here](https://github.com/EverythingMe/redash/compare/DAT-825)), but didn't have the chance to complete. If it's important, I can push it forward in the next two weeks.

**Comment by jcbozonier** [comment]
Oh awesome! Yeah. It's the last big want before we can get this out to everyone in our org. Everyone's psyched to use it.

**Comment by arikfr** [comment]
@jcbozonier got it. will let you know as soon as this is merged.

**Comment by arikfr** [comment]
@jcbozonier #358 was just merged and contains this pull request and some more (see details in its body). Note that to upgrade to the version that contains these changes, you need to run the relevant migration.

**Pull request closed without merging**
