### PR TITLE
Fix: visualizations API fixes

### PR DESCRIPTION
**Pull request by arikfr**
* Apply default options when changing visualization type.
* Change title to new when changing visualization type.

### CODE REVIEW

**Comment by arikfr** [comment]
@BrunoSalerno this includes the fix for `defaultOptions`.

**Comment by BrunoSalerno** [comment]
@arikfr great!

**Comment by arikfr** [comment]
@BrunoSalerno this introduced a small bug, but fixed it already in another PR :) so should be safe for you to upgrade.

Btw, are you on Twitter? I want to tweet about this an mention you.

**Comment by BrunoSalerno** [comment]
@arikfr ahh, nice ;) I  hadn't upgraded to the last version. 
My twitter account is @SalernoBr.
BTW, I'm preparing a heatmap mode for the Map visualization. In a couple of days I'll send you the PR.

**Comment by arikfr** [comment]
@BrunoSalerno heatmaps will be great addition! looking forward :-)

**Pull request merged**
